#region Using Directives
using System.Diagnostics.CodeAnalysis;
#endregion

[assembly: SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "MacroUO.ApplicationDialog.#OnFormClosing(System.Windows.Forms.FormClosingEventArgs)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "MacroUO.ApplicationDialog.#PresetsLoad()")]
[assembly: SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "MacroUO.ExceptionDialog.#OnPaint(System.Windows.Forms.PaintEventArgs)")]
[assembly: SuppressMessage("Microsoft.Design", "CA2210:AssembliesShouldHaveValidStrongNames")]
[assembly: SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "System.Windows.Forms.Control.set_Text(System.String)", Scope = "member", Target = "MacroUO.ApplicationDialog.#.ctor()")]
[assembly: SuppressMessage("Microsoft.Maintainability", "CA1505:AvoidUnmaintainableCode", Scope = "member", Target = "MacroUO.ApplicationDialog.#.ctor()")]
[assembly: SuppressMessage("Microsoft.Mobility", "CA1601:DoNotUseTimersThatPreventPowerStateChanges", Scope = "member", Target = "MacroUO.ApplicationDialog.#.ctor()")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "MacroUO.Macro.#MINIMUM_DELAY")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "MacroUO.Macro.#MAXIMUM_NAME_LENGTH")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "MacroUO.Macro.#MAXIMUM_DELAY")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "NAME", Scope = "member", Target = "MacroUO.Macro.#MAXIMUM_NAME_LENGTH")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "MINIMUM", Scope = "member", Target = "MacroUO.Macro.#MINIMUM_DELAY")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "MAXIMUM", Scope = "member", Target = "MacroUO.Macro.#MAXIMUM_DELAY")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "LENGTH", Scope = "member", Target = "MacroUO.Macro.#MAXIMUM_NAME_LENGTH")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "DELAY", Scope = "member", Target = "MacroUO.Macro.#MINIMUM_DELAY")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "DELAY", Scope = "member", Target = "MacroUO.Macro.#MAXIMUM_DELAY")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "MAXIMUM", Scope = "member", Target = "MacroUO.Macro.#MAXIMUM_NAME_LENGTH")]
[assembly: SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "MenuStrip", Scope = "member", Target = "MacroUO.ApplicationDialog.#.ctor()")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "MacroUO.ExceptionDialog.#Show()")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "MacroUO.ExceptionDialog.#ShowDialog()")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "MacroUO.ExceptionDialog.#ShowDialog(System.Windows.Forms.IWin32Window)")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "MacroUO.RenameDialog.#ShowDialog()")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "MacroUO.RenameDialog.#Show()")]
[assembly: SuppressMessage("Microsoft.Usage", "CA1801:ReviewUnusedParameters", MessageId = "owner", Scope = "member", Target = "MacroUO.ExceptionDialog.#ShowDialog(System.Windows.Forms.IWin32Window)")]
[assembly: SuppressMessage("Microsoft.Usage", "CA2201:DoNotRaiseReservedExceptionTypes", Scope = "member", Target = "MacroUO.Program.#HandleException(System.Exception)")]
[assembly: SuppressMessage("Microsoft.Usage", "CA2213:DisposableFieldsShouldBeDisposed", MessageId = "m_Components", Scope = "member", Target = "MacroUO.ApplicationDialog.#Dispose(System.Boolean)")]
